# Aliases for Docker Cli and Docker Compose Cli
# Created by LounisBou

# GLOBAL VARIABLES

# COMMANDS

# Docker
alias d="docker $*"
alias d-images="docker images $*"
alias d-ps="docker ps $*"
alias d-psa="docker ps -a $*"
alias d-exec="docker exec $*"
alias d-stop="docker stop $*"
alias d-start="docker start $*"
alias d-logs="docker logs $*"
alias d-inspect="docker inspect $*"
alias d-kill="docker kill $*"
alias d-rm="docker rm $*"
alias d-rmi="docker rmi $*"
alias d-cp="docker cp $*"
alias d-commit="docker commit $*"
alias d-login="docker login $*"
alias d-logout="docker logout $*"
alias d-tag="docker tag $*"
alias d-push="docker push $*"
alias d-pull="docker pull $*"
alias d-build="docker build $*"
alias d-run="docker run $*"
alias d-network="docker network $*"
alias d-volume="docker volume $*"
alias d-system="docker system $*"
alias d-version="docker version $*"
alias d-info="docker info $*"
alias d-events="docker events $*"
alias d-attach="docker attach $*"
alias d-diff="docker diff $*"
alias d-export="docker export $*"
alias d-import="docker import $*"
alias d-save="docker save $*"
alias d-load="docker load $*"
alias d-update="docker update $*"
alias d-prune="docker prune $*"
alias d-search="docker search $*"

# Docker Compose
alias dc="docker-compose $*"
alias dc-exec="docker-compose exec $*"
alias dc-run="docker-compose run $*"
alias dc-build="docker-compose build $*"
alias dc-logs="docker-compose logs $*"
alias dc-down="docker-compose down $*"
alias dc-ps="docker-compose ps $*"
alias dc-images="docker-compose images $*"
alias dc-version="docker-compose version $*"
alias dc-config="docker-compose config $*"
alias dc-kill="docker-compose kill $*"
alias dc-pull="docker-compose pull $*"
alias dc-up="docker-compose up $*"
alias dc-up-build="docker-compose up --build $*"
alias dc-up-force="docker-compose up --force-recreate $*"
alias dc-up-remove="docker-compose up --remove-orphans $*"
