# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - use_build_context_synchronously
    - always_use_package_imports
    - avoid_dynamic_calls
    - avoid_type_to_string
    - avoid_empty_else
    - avoid_print
    - avoid_annotating_with_dynamic
    - avoid_types_as_parameter_names
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_brace_in_string_interps
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - use_if_null_to_convert_nulls_to_bools
    - unnecessary_getters_setters
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_setters_to_change_properties





analyzer:
  plugins:
    - import_lint

# issues : https://github.com/rrousselGit/freezed/issues/488
# remove warning "The annotation 'JsonSerializable' can only be used on classes."
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:

    invalid_annotation_target: ignore

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true

import_lint:
  rules:
    ui_rule:
      target_file_path: 'ui/**/*.dart'
      not_allow_imports: [ 'components/**/*.dart','ui/**/*.dart' ]
      exclude_imports: [ ]
    components_rule:
      target_file_path: 'components/**/*.dart'
      not_allow_imports: [ 'components/**/*.dart','ui/**/*.dart' ]
      exclude_imports: [ ]
    screens_rule:
      target_file_path: 'screens/**/*.dart'
      not_allow_imports: [ 'components/**/*.dart','ui/**/*.dart' ]
      exclude_imports: [ 'screens/**/*.dart' ,'components/components.dart']
    routes_rule:
      target_file_path: 'routes/routes.dart'
      not_allow_imports: [ '**/*.dart' ]
      exclude_imports: ['screens/screens.dart','**/pages/*_route.dart']