#!/bin/bash

# Get the directory of the pre-commit script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Get the name of the branch that was just merged
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

################################################################################
################################################################################
################################################################################

# List of post-merge hooks to run
source "$SCRIPT_DIR/php/laravel/migration.sh"

################################################################################
################################################################################
################################################################################
